# Generated by Django 4.2.30 on 2026-05-31 13:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lounges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lounge',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='managed_lounges', to=settings.AUTH_USER_MODEL),
        ),
    ]
