# Generated by Django 4.2.30 on 2026-05-31 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lounges', '0001_initial'),
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='lounge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='lounges.lounge'),
        ),
    ]
